language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t timerdmann/docker-complex-react-test ./client

script:
  - docker run -e CI=true timerdmann/docker-complex-react-test npm run test

after_success:
  # build images for all components
  - docker build -t timerdmann/docker-complex-client ./client
  - docker build -t timerdmann/docker-complex-nginx ./nginx
  - docker build -t timerdmann/docker-complex-server ./server
  - docker build -t timerdmann/docker-complex-worker ./worker

  # log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCHER_ID" --password-stdin

  # push the generated images to docker hub
  - docker push timerdmann/docker-complex-client
  - docker push timerdmann/docker-complex-nginx
  - docker push timerdmann/docker-complex-server
  - docker push timerdmann/docker-complex-worker