language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t timerdmann/docker-complex-react-test ./client

script:
  - docker run -e CI=true timerdmann/docker-complex-react-test npm run test

after_success:
  # build images for all components
  - docker build -t timerdmann/docker-complex-client ./client
  - docker build -t timerdmann/docker-complex-nginx ./nginx
  - docker build -t timerdmann/docker-complex-server ./server
  - docker build -t timerdmann/docker-complex-worker ./worker

  # log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push the generated images to docker hub
  - docker push timerdmann/docker-complex-client
  - docker push timerdmann/docker-complex-nginx
  - docker push timerdmann/docker-complex-server
  - docker push timerdmann/docker-complex-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-complex"
  env: "Dockercomplex-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-779743553114"
  bucket_path: "docker-complex"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY